spring.application.name=saju

spring.config.import=optional:file:.env[.properties]
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.api-key=${GROQ_API_KEY}

server.port=${PORT:8080}
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp